# Training
TRAINING_OBJECTIVE = "rl"

# Model hparams
MODEL_DIM = 512
MODEL_NHEADS = 8
MODEL_NLAYERS = 4

# Training hparams
TRAIN_BATCH_SIZE = 128
LR = 5e-4
LINEAR_START_FACTOR = 0.05
LINEAR_TOTAL_ITERS = 30
COSINE_TMAX = 5000
COSINE_ETA_MIN = 0.1 * LR
SCHEDULER_MILESTONES = [30]

# Addition data hparams
NUM_DATA = 50000
MAX_INT = 1000
TRAIN_SPLIT = 0.94
VAL_SPLIT = 0.03
TEST_SPLIT = 0.03

EXP_NAME = (
    f"model_d{MODEL_DIM}_nh{MODEL_NHEADS}_nl{MODEL_NLAYERS}_add_data_num{NUM_DATA}_max{MAX_INT}_"
    f"train_bs{TRAIN_BATCH_SIZE}_lr{LR}_lin_sf{LINEAR_START_FACTOR}_itr{LINEAR_TOTAL_ITERS}_"
    f"cos_tm{COSINE_TMAX}_min{COSINE_ETA_MIN}_mil{SCHEDULER_MILESTONES}"
)

VAL_BATCH_SIZE = 64
VAL_EVERY_NSTEPS = 50
SAVE_EVERY_NSTEPS = 10000
MODEL_LOAD_PATH = None
